### ISSUE TITLE
missing property: serilization.lib

### ISSUE THREAD

**Issue by JonathanBennett** [treasure-data/prestogres#26]
Hi there,

Today inexplicably (as far as I currently know) the following error stopped our prestogres adapter being able to talk to Presto:

STATEMENT:  select 1 from (select prestogres_catalog.setup_system_catalog(E'[redacted]', E'[redacted]', E'presto', E'default', E'pg')) s;
2015-02-04 00:00:02: pid 21280: FATAL:  Backend throw an error message
2015-02-04 00:00:02: pid 21280: DETAIL:  Exiting current session because of an error from backend
2015-02-04 00:00:02: pid 21280: HINT:  BACKEND Error: "presto_client.PrestoQueryException: Query 20150204_000002_00000_aj2wj failed: missing property: serialization.lib"
2015-02-04 00:00:02: pid 21280: CONTEXT:  while searching system catalog, When relcache is missed

If I execute any query I get the above error message. If I execute the same query through the presto-cli it works as expected.

As far as I'm aware there have been no changes made to prestogres, but I have tried a fresh pull and build to check, but no joy.

Any pointers would be greatly appreciated as I don't see this in the docs but may be something quite intricate too.

Thanks.

**Comment by frsyuki** [comment]
I haven't seem the error message. Because the message includes query id (`20150204_000002_00000_aj2wj`), the message is created by Presto. So Presto thought "serialization.lib" is a missing property.

`setup_system_catalog` runs this query before running the actual query you issued:

```
select table_schema, table_name, column_name, is_nullable, data_type
from information_schema.columns
```

Can you run this query using presto-cli?
Here is the document about the query: https://github.com/treasure-data/prestogres#i-can-connect-to-prestogres-but-cannot-run-any-queries

**Comment by JonathanBennett** [comment]
Turns out this was related to a bug in presto. For interest the issue is logged here; https://github.com/facebook/presto/issues/2317
